# mostra la finestra del browser di file/cartelle
openview_treerepo_node_index:
    pattern:  /repo/browse/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Node:index, nodeid: null }

openview_treerepo_node_newfolder:
    pattern:  /repo/node/newfolder/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Node:newFolder, nodeid: null }
    options:
        expose: true

# mostra il wizard per modificare i metadata dei nodi
openview_treerepo_metadata_editwizard:
    pattern:  /repo/node/metadatawizard/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Metadata:editWizard, nodeid: null }
    options:
        expose: true

# lancia edit/creazione dynamic document con i metadata di un nodo
openview_treerepo_metadata_edit:
    pattern:  /repo/node/metadatawizard/edit/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Metadata:edit }

# lancia eliminazione dynamic document con i metadata di un nodo
openview_treerepo_metadata_delete:
    pattern:  /repo/node/metadatawizard/delete/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Metadata:delete }

# avvia la ricerca nel repository di documenti
openview_treerepo_search:
    pattern:  /repo/search/{terms}
    defaults: { _controller: OpenviewTreeRepoBundle:Search:search }
    options:
        expose: true


#
# rpc per chiamate ajax
#


# ritorna elenco directory figlie della dir. passata
openview_treerepo_node_rpclistdir:
    pattern:  /repo/listdir/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Node:rpcListDir, nodeid: null }
    options:
        expose: true

# ritorna elenco file in una directory
openview_treerepo_node_rpclistfile:
    pattern:  /repo/listfile/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Node:rpcListFile, nodeid: null }
    options:
        expose: true

# dopo l'upload nella dir temporanea, crea il nodo e carica il file nel gridFS
openview_treerepo_node_rpcaddnode:
    pattern:  /repo/addnode/{parentid}/{filename}
    defaults: { _controller: OpenviewTreeRepoBundle:Node:rpcAddNode }
    options:
        expose: true

openview_treerepo_metadata_rpcsetfiletype:
    pattern:  /repo/node/metadatawizard/rpcsetfiletype/{nodeid}/{filetypeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Metadata:rpcSetFiletype }
    options:
        expose: true

openview_treerepo_metadata_rpcgetmetadata:
    pattern:  /repo/node/metadatawizard/rpcgetmetadata/{nodeid}
    defaults: { _controller: OpenviewTreeRepoBundle:Metadata:rpcGetMetadata }
    options:
        expose: true
        

#
# rendering invoacti dai twig
#
openview_treerepo_metadata_rendernodeidfromdyndocid:
    pattern:  /repo/node/metadatawizard/rendernodeidfromdyndocid/{dyndocid}
    defaults: { _controller: OpenviewTreeRepoBundle:Metadata:renderNodeIdFromDynDocId }


        
#
# area amministrativa
#
openview_treerepo_admin:
    pattern:  /admin/repo/index.html
    defaults: { _controller: OpenviewTreeRepoBundle:Admin:index }