parameters:
#    openview_tree_repo.example.class: Openview\TreeRepoBundle\Example

services:
    # KernelRequest listener
    #extension.listener:
    #    class: Openview\TreeRepoBundle\Listener\DoctrineExtensionListener
    #    calls:
    #        - [ setContainer, [ @service_container ] ]
    #    tags:
    #        # translatable sets locale after router processing
    #        - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
    #        # loggable hooks user username if one is in security context
    #        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
